// Koordinat pusat benua
const continentCoords: Record<string, { latitude: number; longitude: number }> =
  {
    Asia: { latitude: 34.0479, longitude: 100.6197 },
    Europe: { latitude: 54.526, longitude: 15.2551 },
    Africa: { latitude: 8.7832, longitude: 34.5085 },
    "North America": { latitude: 54.526, longitude: -105.2551 },
    "South America": { latitude: -8.7832, longitude: -55.4915 },
    Oceania: { latitude: -22.7359, longitude: 140.0188 },
    Antarctica: { latitude: -82.8628, longitude: 135.0 },
  };

// Mapping lengkap negara ke benua
export const countryToContinent: Record<string, string> = {
  Afghanistan: "Asia",
  Albania: "Europe",
  Algeria: "Africa",
  "American Samoa": "Oceania",
  Andorra: "Europe",
  Angola: "Africa",
  Anguilla: "North America",
  Antarctica: "Antarctica",
  "Antigua and Barbuda": "North America",
  Argentina: "South America",
  Armenia: "Asia",
  Aruba: "North America",
  Australia: "Oceania",
  Austria: "Europe",
  Azerbaijan: "Asia",
  Bahamas: "North America",
  Bahrain: "Asia",
  Bangladesh: "Asia",
  Barbados: "North America",
  Belarus: "Europe",
  Belgium: "Europe",
  Belize: "North America",
  Benin: "Africa",
  Bermuda: "North America",
  Bhutan: "Asia",
  Bolivia: "South America",
  "Bosnia and Herzegovina": "Europe",
  Botswana: "Africa",
  Brazil: "South America",
  Brunei: "Asia",
  Bulgaria: "Europe",
  "Burkina Faso": "Africa",
  Burundi: "Africa",
  "Cabo Verde": "Africa",
  Cambodia: "Asia",
  Cameroon: "Africa",
  Canada: "North America",
  "Cayman Islands": "North America",
  "Central African Republic": "Africa",
  Chad: "Africa",
  Chile: "South America",
  China: "Asia",
  "Christmas Island": "Oceania",
  "Cocos (Keeling) Islands": "Oceania",
  Colombia: "South America",
  Comoros: "Africa",
  Congo: "Africa",
  "Congo (Democratic Republic of the)": "Africa",
  "Cook Islands": "Oceania",
  "Costa Rica": "North America",
  Croatia: "Europe",
  Cuba: "North America",
  Curaçao: "North America",
  Cyprus: "Asia",
  Czechia: "Europe",
  Denmark: "Europe",
  Djibouti: "Africa",
  Dominica: "North America",
  "Dominican Republic": "North America",
  Ecuador: "South America",
  Egypt: "Africa",
  "El Salvador": "North America",
  "Equatorial Guinea": "Africa",
  Eritrea: "Africa",
  Estonia: "Europe",
  Eswatini: "Africa",
  Ethiopia: "Africa",
  "Falkland Islands": "South America",
  "Faroe Islands": "Europe",
  Fiji: "Oceania",
  Finland: "Europe",
  France: "Europe",
  "French Guiana": "South America",
  "French Polynesia": "Oceania",
  Gabon: "Africa",
  Gambia: "Africa",
  Georgia: "Asia",
  Germany: "Europe",
  Ghana: "Africa",
  Gibraltar: "Europe",
  Greece: "Europe",
  Greenland: "North America",
  Grenada: "North America",
  Guadeloupe: "North America",
  Guam: "Oceania",
  Guatemala: "North America",
  Guernsey: "Europe",
  Guinea: "Africa",
  "Guinea-Bissau": "Africa",
  Guyana: "South America",
  Haiti: "North America",
  Honduras: "North America",
  "Hong Kong": "Asia",
  Hungary: "Europe",
  Iceland: "Europe",
  India: "Asia",
  Indonesia: "Asia",
  Iran: "Asia",
  Iraq: "Asia",
  Ireland: "Europe",
  "Isle of Man": "Europe",
  Israel: "Asia",
  Italy: "Europe",
  "Ivory Coast": "Africa",
  Jamaica: "North America",
  Japan: "Asia",
  Jersey: "Europe",
  Jordan: "Asia",
  Kazakhstan: "Asia",
  Kenya: "Africa",
  Kiribati: "Oceania",
  Korea: "Asia",
  Kuwait: "Asia",
  Kyrgyzstan: "Asia",
  Laos: "Asia",
  Latvia: "Europe",
  Lebanon: "Asia",
  Lesotho: "Africa",
  Liberia: "Africa",
  Libya: "Africa",
  Liechtenstein: "Europe",
  Lithuania: "Europe",
  Luxembourg: "Europe",
  Macao: "Asia",
  Madagascar: "Africa",
  Malawi: "Africa",
  Malaysia: "Asia",
  Maldives: "Asia",
  Mali: "Africa",
  Malta: "Europe",
  "Marshall Islands": "Oceania",
  Martinique: "North America",
  Mauritania: "Africa",
  Mauritius: "Africa",
  Mayotte: "Africa",
  Mexico: "North America",
  Micronesia: "Oceania",
  Moldova: "Europe",
  Monaco: "Europe",
  Mongolia: "Asia",
  Montenegro: "Europe",
  Montserrat: "North America",
  Morocco: "Africa",
  Mozambique: "Africa",
  Myanmar: "Asia",
  Namibia: "Africa",
  Nauru: "Oceania",
  Nepal: "Asia",
  Netherlands: "Europe",
  "New Caledonia": "Oceania",
  "New Zealand": "Oceania",
  Nicaragua: "North America",
  Niger: "Africa",
  Nigeria: "Africa",
  Niue: "Oceania",
  "Norfolk Island": "Oceania",
  "North Macedonia": "Europe",
  Norway: "Europe",
  Oman: "Asia",
  Pakistan: "Asia",
  Palau: "Oceania",
  Palestine: "Asia",
  Panama: "North America",
  "Papua New Guinea": "Oceania",
  Paraguay: "South America",
  Peru: "South America",
  Philippines: "Asia",
  "Pitcairn Islands": "Oceania",
  Poland: "Europe",
  Portugal: "Europe",
  "Puerto Rico": "North America",
  Qatar: "Asia",
  Réunion: "Africa",
  Romania: "Europe",
  Russia: "Europe",
  Rwanda: "Africa",
  "Saint Barthélemy": "North America",
  "Saint Helena": "Africa",
  "Saint Kitts and Nevis": "North America",
  "Saint Lucia": "North America",
  "Saint Martin": "North America",
  "Saint Pierre and Miquelon": "North America",
  "Saint Vincent and the Grenadines": "North America",
  Samoa: "Oceania",
  "San Marino": "Europe",
  "Sao Tome and Principe": "Africa",
  "Saudi Arabia": "Asia",
  Senegal: "Africa",
  Serbia: "Europe",
  Seychelles: "Africa",
  "Sierra Leone": "Africa",
  Singapore: "Asia",
  "Sint Maarten": "North America",
  Slovakia: "Europe",
  Slovenia: "Europe",
  "Solomon Islands": "Oceania",
  Somalia: "Africa",
  "South Africa": "Africa",
  "South Georgia and the South Sandwich Islands": "Antarctica",
  "South Sudan": "Africa",
  Spain: "Europe",
  "Sri Lanka": "Asia",
  Sudan: "Africa",
  Suriname: "South America",
  Sweden: "Europe",
  Switzerland: "Europe",
  Syria: "Asia",
  Taiwan: "Asia",
  Tajikistan: "Asia",
  Tanzania: "Africa",
  Thailand: "Asia",
  "Timor-Leste": "Asia",
  Togo: "Africa",
  Tokelau: "Oceania",
  Tonga: "Oceania",
  "Trinidad and Tobago": "North America",
  Tunisia: "Africa",
  Turkey: "Asia",
  Turkmenistan: "Asia",
  "Turks and Caicos Islands": "North America",
  Tuvalu: "Oceania",
  Uganda: "Africa",
  Ukraine: "Europe",
  "United Arab Emirates": "Asia",
  "United Kingdom": "Europe",
  "United States": "North America",
  Uruguay: "South America",
  Uzbekistan: "Asia",
  Vanuatu: "Oceania",
  "Vatican City": "Europe",
  Venezuela: "South America",
  Vietnam: "Asia",
  "Wallis and Futuna": "Oceania",
  "Western Sahara": "Africa",
  Yemen: "Asia",
  Zambia: "Africa",
  Zimbabwe: "Africa",
};

// Fungsi generate cooperationMap
export function generateCooperationMap(
  rawData: Record<string, { mou: number; moa: number; ia: number }>,
) {
  const aggregated: Record<string, number> = {};

  for (const [country, values] of Object.entries(rawData)) {
    const continent = countryToContinent[country];
    if (!continent) continue;
    const total = values.mou + values.moa + values.ia;
    aggregated[continent] = (aggregated[continent] || 0) + total;
  }

  return Object.entries(aggregated).map(([continent, total]) => ({
    title: continent,
    latitude: continentCoords[continent].latitude,
    longitude: continentCoords[continent].longitude,
    value: total,
  }));
}
